---
apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: mysql
  # Label sehingga kita bisa bind sebuah Service ke Pod ini
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: database
        image: mysql:5.7
        resources:
          requests:
            memory: 1Gi
        args:
          # Kita membutuhkan ini untuk mencegah mysql dari failure -- DigitalOcean Volumes (block storages) akan di mount disini.
          - "--ignore-db-dir=lost+found"
        # Cara yang efektif untuk mendapatkan sejumlah nilai dari k8s secret kedalam container environment variables
        envFrom:
          - secretRef:
              name: wp-db-secrets
        ## Cara Lama (satu untuk setiap nilai):
        # env:
        # # Gunakan secret, hindari menggunakan plaintext password disetiap config yang kita miliki
        # - name: MYSQL_ROOT_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: wp-db-secrets
        #       key: MYSQL_ROOT_PASSWORD
        livenessProbe:
          tcpSocket:
            port: 3306
        ports:
          - containerPort: 3306
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-volume
