apiVersion: v1

# INSTRUKSI:
# Generate MYSQL_PASSWORD dan MYSQL_ROOT_PASSWORD dan simpan file sebelum digunakan.
# contoh.
# echo && PASS=$(cat /dev/urandom | env LC_CTYPE=C tr -dc [:alnum:] | head -c 15) && echo "Password: ${PASS}" && echo "Base64 encoded:" $(echo ${PASS} | base64)

kind: Secret
metadata:
  name: wp-db-secrets
  namespace: default

type: Opaque

data:
  # Contoh jika kita perlu banyak nilai
  # MYSQL_DATABASE: d29yZHByZXNzCg==
  # MYSQL_USER: d29yZHByZXNzCg==
  # MYSQL_PASSWORD: SXhCMzRxRXF0dERubXpR

  # ini adalah nilai base64 encoded -- Password aslinya adalah NGiJi6A46YJTjTx
  MYSQL_ROOT_PASSWORD: TkdpSmk2QTQ2WUpUalR4
